version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --replicaof no one --slaveof no one
    volumes:
      - redis_data:/data
    networks:
      - shared-network
    restart: unless-stopped

  telegram:
    build: .
    container_name: telegram
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true

volumes:
  redis_data: